from googletrans import Translator, LANGUAGES
translator = Translator()
print ("\n\n")
print ("Selamat datang di".center(50))
print ("Program Pendeteksi Bahasa Terlengkap".center(50))
print ("==================================================")
text = input("Masukkan Text : ")
bahasa = input("Terjemahkan ke Bahasa : ")  
print ("==================================================")
print ("HASILNYA:")
hasil = translator.translate(text,dest=bahasa)
print("Dari",LANGUAGES[hasil.src],": ", text)
print("Ke",LANGUAGES[hasil.dest],": ", hasil.text)
print("Pronounsiasi : ", hasil.pronunciation)
print ("==================================================")
print ("Terima Kasih Banyak :)".center(50))
print ("Created By: Rivant Dwi Seftavianto\n\n".center(50))